(source gnu)
(source melpa)

(package "graphene" "@VERSION" "Friendly Emacs defaults")

(depends-on "company" "0.8.12")
(depends-on "flycheck" "0.23")
(depends-on "graphene-meta-theme" "0.0.2")
(depends-on "smartparens" "1.8.0")
(depends-on "web-mode" "11.2")
(depends-on "smex" "3.0")
(depends-on "ido-completing-read+" "4.3")
(depends-on "sr-speedbar" "20140505")
(depends-on "ppd-sr-speedbar" "0.0.6")
(depends-on "exec-path-from-shell" "1.9")
(depends-on "dash" "2.10.0")
